### ISSUE TITLE
so库报错

### ISSUE THREAD

**Issue by wuaoke** [xiaoyanger0825/NiceVieoPlayer#125]
#6403 java.lang.UnsatisfiedLinkError

    dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.chadaodian.chadaoforandroid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.chadaodian.chadaoforandroid-1/lib/arm64, /system/fake-libs64, /data/app/com.chadaodian.chadaoforandroid-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libijkffmpeg.so"
    com.xiao.nicevideoplayer.NiceVideoPlayer.initMediaPlayer(NiceVideoPlayer.java:362)

解决方案

报这个错误通常是so库加载失败，或者找不到准备执行的JNI方法：
1.建议检查so在安装的过程中是否丢失，没有放入指定的目录下；
2.调用loadLibrary时检查是否调用了正确的so文件名，并对其进行捕获，进行相应的处理，防止程序发生崩溃；
3.检查下so的架构是否跟设备架构一至（如在64-bit架构下调用32-bit的so）。

**Comment by zhushi91** [comment]
工程里面没有看到哪里引入so库啊？

**Comment by wuaoke** [comment]
是呀，所以这个问题相当难受

**Comment by letyourdreamfly** [comment]
楼上大神
问题解决了吗？这边遇到了同样的问题

**Comment by wuaoke** [comment]
没解决，我已经放弃用这个库了，项目里也把上传视频删除了

**Comment by letyourdreamfly** [comment]
没有发现问题，就直接把2.2版本换成了2.1
我们这个视屏高度可以实现自适应吗？暂时没有看到方法

**Comment by wuaoke** [comment]
你用老版本没问题吗？要是没问题，我打算再试试

**Comment by xiaozhao0331** [comment]
大哥们  这个问题解决了么   教我一下

**Comment by jszmd** [comment]
将ndk {
            abiFilters 'armeabi', 'armeabi-v7a', 'x86'
        }复制到自己的项目build.gradle文件下defaultConfig里面

**Comment by Muhammad-Aliii** [comment]
Who are you???

**Comment by XD-Z** [comment]
这个问题搞了半天，依然没解决，不知道有没有最终的解决方式，如果有请回复下，如果没有，能推荐一个好点的库吗？万分感谢

**Comment by xiaozhao0331** [comment]
我最终解决了 是跟项目中的其他直播sdk冲突导致了  最初导入的时候被我ex掉了

**Comment by XD-Z** [comment]
没办法了，我也只能换库了，一样的代码，就是不能运行，太难受了

**Comment by wuaoke** [comment]
已经放弃了，正在学习c中，准备自己弄




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"赵爽"<notifications@github.com&gt;;
发送时间:&nbsp;2019年7月17日(星期三) 晚上8:49
收件人:&nbsp;"xiaoyanger0825/NiceVieoPlayer"<NiceVieoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"build"<987603594@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaoyanger0825/NiceVieoPlayer] so库报错 (#125)




大哥们  这个问题解决了么   教我一下
