### ISSUE TITLE
在播放相同url的视频时会同时播放视频

### ISSUE THREAD

**Issue by qSunJ** [xiaoyanger0825/NiceVieoPlayer#16]
当列表中两个视频的url相同，会同时播放，这个怎么解决

**Comment by xiaoyanger0825** [comment]
demo中的列表有相同url的视频，我这边测试没有同时播放呢，可以详细描述一下你遇到Bug的情况不呢？

**Comment by 153108317** [comment]
我也遇到这个问题，我用的是listview，应该是view复用问题，怎么处理呢？

**Comment by xiaoyanger0825** [comment]
目前测试ListView中还存在一些Bug，ListView完全可以用RecyclerView代替，建议使用RecyclerView

**Comment by xiaoyanger0825** [comment]
@153108317
