### ISSUE TITLE
你好,为什么该视频播放器在点击全屏播放时会奔溃

### ISSUE THREAD

**Issue by twentyT** [xiaoyanger0825/NiceVieoPlayer#18]

**Comment by xiaoyanger0825** [comment]
什么机型和系统呢，看下崩溃日志呢？

**Comment by twentyT** [comment]
华为手机 6.0系统  MEUI系统4.1.1    没有奔溃日志- -

**Comment by xiaoyanger0825** [comment]
是v1.6版本嘛，用的是默认的MediaPlayer还是IjkPlayer？

**Comment by twentyT** [comment]
恩,是V1.6版本,用的是默认的MediaPlayer还是IjkPlayer?这句我看不懂  用的是这个com.xiao.nicevideoplayer.NiceVideoPlayer

**Comment by xiaoyanger0825** [comment]
那你应该是没有改过demo，我先找个华为手机测试一下哈

**Comment by twentyT** [comment]
恩恩,大牛方不方便加我QQ位置微信教我,QQ:583032574  微信:d583032574
