### ISSUE TITLE
快进或快退部是在缓冲

### ISSUE THREAD

**Issue by shaodong2528** [xiaoyanger0825/NiceVieoPlayer#19]
我有一个视频大概300多M只有10分钟左右，使用ijk播放会出现黑屏有声音，如果使用mediaplay就正常，但快进或快退就是老是缓冲，播放时一两秒就缓冲，而且画面是停暂的画面，上面ijdk播放黑屏是正常现像我用其它基于ijd播放器播放也一样，因为这个视频是压缩过的可能没有按h264格式压缩，我想知道这个mediaplay快进快退问题有办法解决吗。

**Comment by xiaoyanger0825** [comment]
黑屏有声音应该是你视频文件压缩的时候有损坏，MediaPlayer播放一两秒就缓冲这应该是正常的，因为MediaPlayer播放网络视频本来加载就慢，10分钟300兆的视频算比较大的了，如果网速不是很快的话，MediaPlayer确实会进程出现缓冲的情况。

**Comment by shaodong2528** [comment]
应该跟网速没关系，我用手机显示网速可以看到速度有时有1、2M,而且我这个视频现在只部署在本地，不过放其它正常的视频没发现问题，就是对于这种视频很大又只有几分钟的情况后期可能需要再优化下.

**Comment by xiaoyanger0825** [comment]
本地视频直接传本地文件的路径就可以了 Environment.getExternalStorageDirectory().getPath() + "/文件所在子目录/../你的文件名.*"
