### ISSUE TITLE
exoplayer 版本怎么样了  建议不ijkplayer 因为对m3u8 支持有问题

### ISSUE THREAD

**Issue by xiongcandejitui** [xiaoyanger0825/NiceVieoPlayer#2]

**Comment by xiaoyanger0825** [comment]
exo的api和原生的有些差异，暂时先实现Ijk的，后续会添加exo的支持。

**Comment by xiongcandejitui** [comment]
我已经在你的基础上实现了exo的了 ijk对m3u8支持很渣， 没有使用价值 你只要使用 ijk-exo这个库，就可以以mediaplayer的形式接入exo 不用改一行代码

**Comment by xiongcandejitui** [comment]
compile 'tv.danmaku.ijk.media:ijkplayer-exo:0.8.0'

**Comment by xiongcandejitui** [comment]
对了，期望能加入 手势快进快退 标准|高清|超清片源选择 功能

**Comment by xiaoyanger0825** [comment]
我又看了一下ijk-exo，播放状态和MediaPlayer/IjkPlayer稍微有一点差异，主要是onPrepared那。后续的功能会逐渐添加。

**Comment by hy20160705** [comment]
我来挖坟了  对m3u8的支持有没有加进去呀 我这边播放m3u8的流时  一直处于加载中  求指教

**Comment by manondidi** [comment]
https://github.com/CarGuo/GSYVideoPlayer
我现在用这个 底层是ijk 和exo 都可以的
特效也做得很棒

**Comment by hy20160705** [comment]
哇  可以可以  吃饭回来我就试试  谢谢谢谢
