### ISSUE TITLE
分享和在家图标

### ISSUE THREAD

**Issue by twentyT** [xiaoyanger0825/NiceVieoPlayer#27]
你好,请问分享和加载图标怎么搞

**Comment by xiaoyanger0825** [comment]
什么意思呢？

**Comment by twentyT** [comment]
视频播放完成后页面上有一个分享按钮,点击弹出一个toast,这个方法能调出来吗?还是加载缓冲的时候的图标可不可以自己改动呢

**Comment by xiaoyanger0825** [comment]
TxVideoPlayerController是我写的一个类时腾讯视频热点列表页的播放控制器的样例，一般都不会直接用的，你可以按照TxVideoPlayerController来继承自NiceVideoPlayerController来写，把里面的点击分享的逻辑改成自己的，其他的那些图标都可以换成自己的

**Comment by twentyT** [comment]
谢谢啦

**Comment by xiaoyanger0825** [comment]
不客气，当然，你自己定义的时候可以将分享回调出来，这样也好处理。
