### ISSUE TITLE
请问niceviewoplayer中去除ijk依赖有影响吗？

### ISSUE THREAD

**Issue by buluojava** [xiaoyanger0825/NiceVieoPlayer#3]
找了很多第三方发现还是原生对rtsp支持得比较好，想只保留MediaPlayer + TextureView，而且TextureView实现截图功能十分方便，加上我不需要小窗播放是不是不实现addOnChildAttachStateChangeListener就好了。
抱歉时间匆忙还没看代码就提问。

**Comment by xiaoyanger0825** [comment]
这个去除的话，就需要修改NiceVideoPlayer里面的部分代码，把所有的IMediaPlayer全部改成MediaPlayer即可，api都是一样的。
