### ISSUE TITLE
播放后界面绿屏

### ISSUE THREAD

**Issue by CrazyTaro** [xiaoyanger0825/NiceVieoPlayer#30]
在播放完成后,没有做任何操作时,界面会变成绿屏.
在全屏播放时暂停,退回到原来窗口大小时,界面也会变成绿屏.

查了源码,添加textureView虽然是有调用到`addView(view,index)`,把textureView添加到第一个view的位置,但是并不能正常显示出来.视频缩略图还是会完全"挡住"播放画面. PS,demo并不存在这个问题,但是代码基本跟Demo是一样的.

**Comment by xiaoyanger0825** [comment]
hello，你是直接用的TxVideoPlayer吗，有没有改动过里面的逻辑呢？还有就是绿屏是整个播放界面都变成绿色还是整个应用界面呢？

**Comment by CrazyTaro** [comment]
不是直接用的txController,因为UI不太一样所以是继承默认的controller自定义的.但逻辑基本是参考txController实现的.因为并不需要到那么复杂的逻辑.
仅播放的界面是变绿屏,不是整个应用. 应该是textureView的部分是绿屏.

**Comment by xiaoyanger0825** [comment]
那有可能是自定义的controller里面根据onPlayStateChanged方法来改变界面UI的逻辑有些问题，TxNiceVideoPlayerController播放完成后是有一层完成的UI遮住下面的TextureView的。

**Comment by CrazyTaro** [comment]
看到了, 功能不太一样所以没有全部代码都复用,之前看的时候没注意到播放时隐藏的缩略图和播放后显示出来的缩略图.
谢谢~

**Comment by xiaoyanger0825** [comment]
客气。
