### ISSUE TITLE
如何铺满播放啊？

### ISSUE THREAD

**Issue by buluojava** [xiaoyanger0825/NiceVieoPlayer#35]
就是不让播放出现左右或者上下有黑边的情况，视频是铺满view播放的

**Comment by buluojava** [comment]
通过mTextureView.adaptVideoSize解决了，不知道算不算蛮力解决，如果有更好的办法麻烦告诉我一下~~~~

**Comment by xiaoyanger0825** [comment]
mTextureView.adaptVideoSize这个方法本来是为了适应视频按照原比例缩放，如果使用这个来让视频铺满的话会导致视频宽高比例缩放不一致，建议通过视频的宽高比例来改变NiceVideoPlayer的宽高，这样比较好，在demo中视频列表的适配器ViewHolder里面有一示例。
