### ISSUE TITLE
视图设置

### ISSUE THREAD

**Issue by dongpingy** [xiaoyanger0825/NiceVieoPlayer#38]
mNiceVideoPlayer视图设置wrap_content的时候TxVideoPlayerController的控制视图被撑开到上下位置

**Comment by xiaoyanger0825** [comment]
TxVideoPlayerController不能设置包裹哦，因为全屏或小屏的时候要自动撑开到父布局的大小的哈

**Comment by xiaoyanger0825** [comment]
要设置成match_parent
