### ISSUE TITLE
视频处理方式情况

### ISSUE THREAD

**Issue by yangjiangs** [xiaoyanger0825/NiceVieoPlayer#40]
视频宽小于视频的高，出现位置有问题
![image](https://user-images.githubusercontent.com/13154138/28604923-e088b508-7200-11e7-809e-eca2b0e69522.png)

**Comment by xiaoyanger0825** [comment]
可否提供一下视频链接，我测试一下呢？

**Comment by yangjiangs** [comment]
http://oph6zeldx.bkt.clouddn.com/test0.mp4

**Comment by yangjiangs** [comment]
好的

**Comment by xiaoyanger0825** [comment]
hello，我测试后是这样的呢
![fff](https://user-images.githubusercontent.com/18342788/28609368-f8241e26-7216-11e7-88d3-b6fd77e43bb0.png)
因为 视频本身是高大于宽的，如果直接铺满的话视频会被拉伸影响观看的，所以就按视频本身的比例缩放，并且放到了中间位置，可以参考其他一些列表视频app，都是这样的逻辑。

**Comment by junge89221** [comment]
@xiaoyanger0825 我也遇到了这样的需求，请问怎么设置铺满屏幕呢，用的ijkplayer！我看到官方封装的有个setAspectRatio(IRenderView.AR_ASPECT_FILL_PARENT)的方法，请问niceplayer怎么设置呢~~
