### ISSUE TITLE
IjkExoMediaPlayer和IjkMediaPlayer在播放的时候返回的状态不一致

### ISSUE THREAD

**Issue by hymlv** [xiaoyanger0825/NiceVieoPlayer#41]
onPlayStateChanged(int playState) 是根据播放状态来处理ui等逻辑的,现在发现使用不同的播放引擎处理,返回顺序不一致. IjkExoMediaPlayer 返回的是 1->5->3->2->2  IjkMediaPlayer返回的是 1->2->5->3->3.
导致点击时候,顶部和顶部的操作区域无法正常显示

**Comment by xiaoyanger0825** [comment]
因为exo和ijk及原生MediaPlayer的状态差异，目前暂未支持exo
