### ISSUE TITLE
so库就有25M,太大了吧

### ISSUE THREAD

**Issue by ShineBright2015** [xiaoyanger0825/NiceVieoPlayer#48]
可以选择，或者自己编译so库吗

**Comment by xiaoyanger0825** [comment]
可以，自己编译的替换掉里面的就行了

**Comment by ShineBright2015** [comment]
可以说一下怎么编译才可以将 ijkmmpeg.so变得比较小吗

**Comment by xiaoyanger0825** [comment]
可以直接用编译好的，在gradle中添加依赖就行，那个要小一些，如果自己编译的话，你要参考IJkPlayer的文档了

**Comment by ShineBright2015** [comment]
恩，我看到现在的 ijkmpeg.so有4M多，不知道你说的那个有多大

**Comment by ShineBright2015** [comment]
可以发个编译好的给我吗？最好小一点
