### ISSUE TITLE
播放器播放卡顿

### ISSUE THREAD

**Issue by yuanlvmao** [xiaoyanger0825/NiceVieoPlayer#53]
http://staging.files.app.wutongtech.com/lessonvideo/%E7%8E%AF%E4%BF%9D%E5%B0%8F%E8%A7%86%E9%A2%91.mp4
播放这个url的时候，明显感觉到卡顿，，，一直提示缓冲中，即使缓存了一半也是这样，用的IjkPlayer

**Comment by xiaoyanger0825** [comment]
我这边播放时没带卡顿的问题的哦，缓冲也很快。是不是你的网络问题呢？

**Comment by yuanlvmao** [comment]
应该还是这个视频实在太大了的问题，网络不是特别给力的话，缓冲过慢了，不是程序的问题

**Comment by xiaoyanger0825** [comment]
应该是这样，最好压缩一下视频源
