### ISSUE TITLE
列表播放，返回到首页如何小窗口播放

### ISSUE THREAD

**Issue by nances** [xiaoyanger0825/NiceVieoPlayer#8]
博主您好，我现在在写视频demo，用IJK的播放器，如何冲一个正在播放页面返回到列表页是小窗口播放？烦请告知，谢谢

**Comment by xiaoyanger0825** [comment]
是从全屏播放返回到列表页是小窗口播放吗？

**Comment by nances** [comment]
@xiaoyanger0825  比如说我进入直播间，返回应该是退出去的嘛，我希望是在应用里面的其他页面都是可以显示的

**Comment by xiaoyanger0825** [comment]
@nances 意思就是再各个Activity跳转后都还是能看到小窗口在播放视频？

**Comment by xiaoyanger0825** [comment]
如果是需要在各个页面之间跳转能一直有小窗口在播放，可以考虑跳转的其他页面用Fragment做，主要的就一个Activity应该可以。

**Comment by nances** [comment]
@xiaoyanger0825  是这个意思，每个窗口都可以看到视频播放，不知道博主能否提供一个好思路，谢谢

**Comment by xiaoyanger0825** [comment]
我想这样应该可以，就按照NiceVideoPlayer现在的视频小窗口播放逻辑，各个跳转页面都放在当前的Activity中，各个页面的跳转就是fragment的跳转，这样应该能保证fragment在跳转的时候不影响前面的视频小窗口。

**Comment by nances** [comment]
@xiaoyanger0825  博主 能否可以把这个效果加上  🙏

**Comment by xiaoyanger0825** [comment]
我下个版本写一个demo

**Comment by nances** [comment]
@xiaoyanger0825  谢谢博主了....
